version: "3.9"

services:
  redis:
    container_name: task-mgmt-redis
    image: redis:latest
    restart: always
    ports:
      - "6379:6379"
    environment:
      - REDIS_PASSWORD=my-password
      - REDIS_PORT=6379
      - REDIS_DATABASES=16
  postgres:
    container_name: task-mgmt-postgres
    image: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - ./setup/init-db.sh:/docker-entrypoint-initdb.d/init-db.sh
  app:
    build: .
    ports:
      - "3000:3000"
    environment:
      - REDIS_URL=redis://task-mgmt-redis:6379
      - DATABASE_URL=postgres://postgres:postgres@task-mgmt-postgres:5432/task_mgmt