version: "3.9"

services:
  redis:
    container_name: task-mgmt-redis
    image: redis:latest
    restart: always
    ports:
      - "6379:6379"
    environment:
      - REDIS_DATABASES=16
  postgres:
    container_name: task-mgmt-postgres
    image: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: task_mgmt
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./drizzle:/docker-entrypoint-initdb.d
  app:
    build: .
    ports:
      - "3000:3000"
    environment:
      - REDIS_URL=redis://redis:6379
      - DATABASE_URL=postgres://postgres:postgres@postgres:5432/task_mgmt
    depends_on:
      - postgres
      - redis

volumes:
  postgres-data:
    driver: local
